
import java.util.Calendar;
import java.util.GregorianCalendar;


public class clockframe extends javax.swing.JFrame {

    int xmouse,ymouse,x,y;
    
    
    public clockframe() {
        initComponents();
        int counter=0;
        new Thread()
        {
           public void run()
          {
            
              while(counter==0)
              {
               Calendar cal=new GregorianCalendar();
               int hour=cal.get(Calendar.HOUR);
               int min=cal.get(Calendar.MINUTE);
               int sec=cal.get(Calendar.SECOND);
               int am_pm=cal.get(Calendar.AM_PM);
               String s;
               if(am_pm==1)
              {   
                  if(sec<10)
                  {
                  s=hour+":"+min+":0"+sec+" PM";
                  }
                  else
                  {
                   s=hour+":"+min+":"+sec+" PM";
                   }
                  clock.setText(s);
               }
               else
              {
                  
                   if(sec<10)
                  {
                  s=hour+":"+min+":0"+sec+" PM";
                  }
                  else
                  {
                   s=hour+":"+min+":"+sec+" PM";
                   }
                  clock.setText(s);
                  
                  s=hour+":"+min+":"+sec+" PM";      
                  clock.setText(s);        
               }
              }
              
          }
                    
        }.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        closelabel = new javax.swing.JLabel();
        clock = new javax.swing.JLabel();
        mlabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.8F);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setLayout(null);

        closelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close1.png"))); // NOI18N
        closelabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                closelabelMouseReleased(evt);
            }
        });
        jPanel1.add(closelabel);
        closelabel.setBounds(410, 10, 20, 20);

        clock.setFont(new java.awt.Font("DS-Digital", 1, 72)); // NOI18N
        clock.setForeground(new java.awt.Color(153, 255, 102));
        clock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clock.setText("2:53:10 PM");
        jPanel1.add(clock);
        clock.setBounds(50, 50, 320, 100);

        mlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/min.png"))); // NOI18N
        mlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mlabelMouseReleased(evt);
            }
        });
        jPanel1.add(mlabel);
        mlabel.setBounds(385, 10, 20, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\suresh\\Documents\\clockbg.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-10, 0, 450, 190);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closelabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closelabelMouseReleased
        System.exit(0);
    }//GEN-LAST:event_closelabelMouseReleased

    private void mlabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mlabelMouseReleased
        this.setState(clockframe.ICONIFIED);
    }//GEN-LAST:event_mlabelMouseReleased

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        x=evt.getXOnScreen();
        y=evt.getYOnScreen();
        this.setLocation(x-xmouse, y-ymouse);
    }//GEN-LAST:event_formMouseDragged

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
   
    }//GEN-LAST:event_formMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
          
       xmouse=evt.getX();
       ymouse=evt.getY();
       
    }//GEN-LAST:event_formMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clockframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clockframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clockframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clockframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clockframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clock;
    private javax.swing.JLabel closelabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mlabel;
    // End of variables declaration//GEN-END:variables
}
